version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: its_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=assessment_db
    ports:
      - "5433:5432"